// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosizeController from "./autosize_controller"
application.register("autosize", AutosizeController)

import Bridge__ButtonController from "./bridge/button_controller"
application.register("bridge--button", Bridge__ButtonController)

import Bridge__NotificationTokenController from "./bridge/notification_token_controller"
application.register("bridge--notification-token", Bridge__NotificationTokenController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import ShiftEnterController from "./shift_enter_controller"
application.register("shift-enter", ShiftEnterController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
